In [43]:
import torch
import torch.nn as nn

seq_len = 5
device = 'cpu'   
max_rel_dist = 3
i = torch.arange(seq_len, device=device).unsqueeze(1)
print(f"i shape: {i.shape}")
j = torch.arange(seq_len, device=device).unsqueeze(0)
print(f"j shape: {j.shape}")

"""
row n, column m is the nth element of i - the mth element of j
so i-j[0,0] should be 0 - 0 = 0, and i-j[3,1] should be 3 - 1 = 2.
"""
print("i-j")
print(i-j)

rel_pos_clamped = (i - j).clamp(-max_rel_dist + 1, max_rel_dist - 1) 

print("rel pos clamped")
print(rel_pos_clamped) 


rel_pos = (i - j).clamp(-max_rel_dist + 1, max_rel_dist - 1) + max_rel_dist - 1
print("rel pos")
print(rel_pos) 

rel_pos_bias = nn.Embedding(2 * max_rel_dist - 1, 1)
rel_bias = rel_pos_bias(rel_pos).squeeze(-1).unsqueeze(0).unsqueeze(0) # shap seq_len x seq_len



i shape: torch.Size([5, 1])
j shape: torch.Size([1, 5])
i-j
tensor([[ 0, -1, -2, -3, -4],
        [ 1,  0, -1, -2, -3],
        [ 2,  1,  0, -1, -2],
        [ 3,  2,  1,  0, -1],
        [ 4,  3,  2,  1,  0]])
rel pos clamped
tensor([[ 0, -1, -2, -2, -2],
        [ 1,  0, -1, -2, -2],
        [ 2,  1,  0, -1, -2],
        [ 2,  2,  1,  0, -1],
        [ 2,  2,  2,  1,  0]])
rel pos
tensor([[2, 1, 0, 0, 0],
        [3, 2, 1, 0, 0],
        [4, 3, 2, 1, 0],
        [4, 4, 3, 2, 1],
        [4, 4, 4, 3, 2]])
Embedding(5, 1)


In [ ]:
rel_pos = (i - j).clamp(-max_rel_dist + 1, max_rel_dist - 1) + max_rel_dist - 1
print(f"rel pos shape: {rel_pos.shape}")

rel_pos_bias = nn.Embedding(2 * max_rel_dist - 1, 1)
rel_bias = rel_pos_bias(rel_pos).squeeze(-1).unsqueeze(0).unsqueeze(0) # shap seq_len x seq_len

In [26]:
print(i-j)

tensor([[ 0, -1, -2, -3, -4],
        [ 1,  0, -1, -2, -3],
        [ 2,  1,  0, -1, -2],
        [ 3,  2,  1,  0, -1],
        [ 4,  3,  2,  1,  0]])


In [22]:
print(rel_pos.shape)

torch.Size([100, 100])


In [18]:
print(rel_pos)

tensor([[49, 48, 47,  ...,  0,  0,  0],
        [50, 49, 48,  ...,  0,  0,  0],
        [51, 50, 49,  ...,  0,  0,  0],
        ...,
        [98, 98, 98,  ..., 49, 48, 47],
        [98, 98, 98,  ..., 50, 49, 48],
        [98, 98, 98,  ..., 51, 50, 49]])


In [17]:
rel_bias[0,0]

tensor([[-0.0653,  2.3162,  0.6533,  ..., -0.7825, -0.7825, -0.7825],
        [ 0.4292, -0.0653,  2.3162,  ..., -0.7825, -0.7825, -0.7825],
        [ 0.6551,  0.4292, -0.0653,  ..., -0.7825, -0.7825, -0.7825],
        ...,
        [ 0.5992,  0.5992,  0.5992,  ..., -0.0653,  2.3162,  0.6533],
        [ 0.5992,  0.5992,  0.5992,  ...,  0.4292, -0.0653,  2.3162],
        [ 0.5992,  0.5992,  0.5992,  ...,  0.6551,  0.4292, -0.0653]],
       grad_fn=<SelectBackward0>)